run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 3
